/**
 * 
 */
package com.homedepot.hs.monitoring.constants;

/**
 * @author syntel
 *
 */
public interface MonitorSqlConstatns {
	
	/*String SQL_SELECT_TREE_DATA = "SELECT * FROM MONITOR.HOMESERVICE_STATUS WHERE TIME >= ? AND TIME <= ?";
	
	String SQL_SELECT_APP_DATA = "SELECT * FROM MONITOR.HOMESERVICE_STATUS WHERE APP_NAME = ? AND  (TIME >= ? AND TIME <= ?)";
	
	String SQL_SELECT_TOP_3_APP_DATA = "SELECT * FROM MONITOR.HOMESERVICE_STATUS WHERE APP_NAME = ? ORDER BY ID DESC LIMIT 3";
	
	String SQL_UPDATE_ROWS_BY_ID ="UPDATE HOMESERVICE_STATUS SET EMAIL_SENT_ST = 'Y' WHERE ID IN(";*/
	
	
	String SQL_SELECT_HDE_TREE_DATA = "SELECT A.*, B.LATENCY_ERROR,B.LATENCY_WARNING,B.ERROR_THRESHHOLD,B.ERROR_WARNING_THRESHHOLD,B.PARENT, B.CHILD FROM HDI_STATUS1 A,  HDI_THRESHOLD B WHERE A.app_NAME= B.APP_NM AND A.TIME >= ? AND A.TIME <= ? AND B.D_APP_NM=? order by id asc";
	
	String SQL_APP_STATUS =" SELECT  B.D_APP_NM, APP_NM, LATENCY FROM HOMESERVICE_STATUS A,  HOMESERVICES_THRESHOLD B  WHERE A.app_NAME= B.APP_NM AND  A.TIME >= ? AND A.TIME <= ? AND D_APP_NM=? AND  A.LATENCY!=1  ORDER BY APP_NM";
	
	String SQL_SELECT_TREE_DATA = "SELECT A.*, B.LATENCY_ERROR,B.LATENCY_WARNING,B.ERROR_THRESHHOLD,B.ERROR_WARNING_THRESHHOLD,B.PARENT, B.CHILD ,B.D_APP_NM FROM HS_PCF_APP_MONIT_STATUS A,  HS_PCF_APP_MONIT_THRESHOLD B WHERE A.app_NAME= B.APP_NM AND A.TIME >= ? AND A.TIME <= ? AND B.D_APP_NM=?";
	
	String SQL_SELECT_FTP_TREE_DATA = "SELECT * FROM HOMESERVICES_THRESHOLD WHERE D_APP_NM=?";
	
	String SQL_SELECT_APP_DATA = "SELECT * FROM HS_PCF_APP_MONIT_STATUS WHERE APP_NAME = ? AND  (TIME >= ? AND TIME <= ?)";
	
	String SQL_SELECT_APP_ERROR = "SELECT * FROM HOMESERVICE_STATUS WHERE  APP_NAME = ? AND STATUS !=200 AND   (TIME >= ? AND TIME <= ?)";
	
	String SQL_SELECT_TOP_3_APP_DATA = "SELECT * FROM HOMESERVICE_STATUS WHERE APP_NAME = ? ORDER BY ID DESC LIMIT 3";
	
	String SQL_UPDATE_ROWS_BY_ID ="UPDATE HOMESERVICE_STATUS SET EMAIL_SENT_ST = 'Y' WHERE ID IN(";
	
	String SQL_SELECT_LAST_UPDATED_DATATIME = "SELECT TIME FROM HS_PCF_APP_MONIT_STATUS ORDER BY TIME DESC LIMIT 1";
	
	String SQL_FTP_STATUS_CHECK ="select A.*, B.* from file_monitoring_status A, homeservices_threshold B WHERE A.app_name=b.app_nm AND time = (select max(time) from file_monitoring_status)";
	
	String SQL_SELECT_DAILY_SALES ="SELECT * FROM SALES_STATUS where APP_NAME = ? ORDER BY UPDATED_TIME DESC LIMIT 1";

	String SQL_SELECT_DAILY_SALES_TREE_DATA = "SELECT * FROM HOMESERVICES_THRESHOLD WHERE D_APP_NM = 'DailySales'";
	
	String SQL_SELECT_FTPS_TREE_DATA = "SELECT * FROM HOMESERVICES_THRESHOLD WHERE D_APP_NM = 'FileMonitoring'";
	
	String SQL_SELECT_FTPS = "SELECT * FROM FILE_MONITORING_STATUS WHERE APP_NAME = ? ORDER BY TIME DESC LIMIT 1";


}
